/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qqgwmogdshwwlalrwruw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZ3dtb2dkc2h3d2xhbHJ3cnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMjA5NTAsImV4cCI6MjA4NjU5Njk1MH0.tZb6ZUjFaKRxtBZ3g2-OTVXF-QmrO1pAt0E3cTTdjsI"